### ISSUE TITLE
Hande exceptions when query is not present in the mapping.

### ISSUE THREAD

**Issue by kmcluskey** [glasgowcompbio/pyMultiOmics#6]
Currently, if a query_id is not found in a Query a KeyError is returned. This is the case when a list is passed no matter how many 'hits' are found. Better exception handling should be used.

**Comment by kmcluskey** [comment]
Fix has been pushed onto branch iss_6

**Comment by kmcluskey** [comment]
Sorry, didn't mean to close.

**Comment by joewandy** [comment]
Fixed by @kmcluskey in https://github.com/glasgowcompbio/pyMultiOmics/pull/7
